name: Build Gradle project
permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write
on:
  push:
jobs:
  build-test:
    name: Build & Test
    if: github.ref == 'Clean-Code-Team/Invaders'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Run build with Gradle Wrapper
      run: ./gradlew build
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Test with Gradle
      run: ./gradlew --info test
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: build/test-results/**/*.xml
